In [1]:
# Berikut ini adalah library yang dibutuhkan untuk proses scraping data review google playstore:
import numpy as np
import pandas as pd
from google_play_scraper import app
from google_play_scraper import Sort, reviews
from google_play_scraper import permissions

In [2]:
# Proses Scraping aplikasi Livin by mandiri
scrap_review, token = reviews(
    'id.bmri.livin',  # ID aplikasi (didapatkan melalui link aplikasi di google)
    lang='id',               
    country='id',              
    sort=Sort.MOST_RELEVANT,   
    count=100, # ambil review sebanyak 100
    filter_score_with=None        
)

In [3]:
# Menampilkan data yang berhasil diambil 
reviewslivin_df = pd.DataFrame(scrap_review)
reviewslivin_df.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,937b3e53-cab9-43a5-965a-a70dda63cc7a,Yuli Ana,https://play-lh.googleusercontent.com/a/ACg8oc...,"Ini Livin lagi kenapa?? Di hp 1 saya, Livin ny...",1,64,3.2.0,2026-02-22 09:44:27,"Halo Sahabat @Yuli Ana, mohon maaf atas ketida...",2026-02-22 09:52:19,3.2.0
1,869deea8-7ac8-4031-96b2-b809cef54029,TuahKurnia,https://play-lh.googleusercontent.com/a-/ALV-U...,programmernya yang buat aplikasi minm literasi...,1,96,3.2.0,2026-01-30 13:46:42,"Halo Sahabat @TuahKurnia, mohon maaf atas keti...",2026-01-30 13:50:15,3.2.0
2,13804282-f07e-4f0e-ab06-5a57a6a2abe2,Azam Zam,https://play-lh.googleusercontent.com/a-/ALV-U...,Gabisa login sudah beberapa kali coba sampe be...,1,214,3.2.0,2026-01-14 20:31:41,"Halo Sahabat @ZAMZAM N, mohon maaf atas ketida...",2026-01-14 20:34:57,3.2.0
3,d5588b56-8872-4603-9d47-9790e1ed57b5,yaomi inaya,https://play-lh.googleusercontent.com/a-/ALV-U...,"Dari awal bikin dipersulit, mau masuk pun juga...",1,195,3.2.0,2026-01-22 11:24:28,"Hai Sahabat @yaomi inaya, mohon maaf atas keti...",2026-01-22 11:27:43,3.2.0
4,824e0cdd-dc40-4f75-aef4-eca931815c72,Azura Agustina,https://play-lh.googleusercontent.com/a-/ALV-U...,Kenapa ya sekarang mandiri di jam-jam tengah m...,2,62,3.2.0,2026-01-16 23:29:04,"Hi Sahabat @Azura Agustina, mohon maaf atas ke...",2026-01-16 23:33:11,3.2.0

In [5]:
# Banyak data yang berhasil diambil
len(reviewslivin_df)

100

In [21]:
# Menampilkan review yang rentangnya dari tanggal 23 Januari 2026 hingga 26 Februari 2026
review2 = reviewslivin_df[(reviewslivin_df['at']>"2026-01-23") & (reviewslivin_df['at']<"2026-02-26")]

review2

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,937b3e53-cab9-43a5-965a-a70dda63cc7a,Yuli Ana,https://play-lh.googleusercontent.com/a/ACg8oc...,"Ini Livin lagi kenapa?? Di hp 1 saya, Livin ny...",1,64,3.2.0,2026-02-22 09:44:27,"Halo Sahabat @Yuli Ana, mohon maaf atas ketida...",2026-02-22 09:52:19,3.2.0
1,869deea8-7ac8-4031-96b2-b809cef54029,TuahKurnia,https://play-lh.googleusercontent.com/a-/ALV-U...,programmernya yang buat aplikasi minm literasi...,1,96,3.2.0,2026-01-30 13:46:42,"Halo Sahabat @TuahKurnia, mohon maaf atas keti...",2026-01-30 13:50:15,3.2.0
5,1831c09c-64a7-4160-be77-386261e169a9,Seorang Manusia,https://play-lh.googleusercontent.com/a-/ALV-U...,Tolong segera diperbaiki! Fitur Login mengguna...,2,21,3.2.0,2026-01-31 18:39:28,"Halo Sahabat @Seorang Manusia, mohon maaf atas...",2026-01-31 18:41:57,3.2.0
6,099f964e-c634-4475-beaf-3f9ae7aa8b81,Budi Setiawan Sembiring,https://play-lh.googleusercontent.com/a-/ALV-U...,Ini aplikasi niat jualan fitur atau niat nyiks...,1,9,3.2.0,2026-02-17 11:33:37,"Halo Sahabat @Budi Setiawan Sembiring, mohon m...",2026-02-17 11:55:44,3.2.0
8,4d84e8a0-889c-43d5-8c7d-c722a4200b29,Maya Adetya,https://play-lh.googleusercontent.com/a-/ALV-U...,Biometrik untuk login tiba-tiba non aktif send...,1,77,3.2.0,2026-02-14 16:46:17,"Hai Sahabat @Maya Adetya, mohon maaf atas keti...",2026-02-14 16:49:15,3.2.0
...,...,...,...,...,...,...,...,...,...,...,...
95,7f76760d-5c4e-462e-ac8d-e3727a45d5d1,Iwan Apriadi,https://play-lh.googleusercontent.com/a-/ALV-U...,"Saya Baca Semua Keluhan Konsumen , Hampir Semu...",1,1,3.2.0,2026-01-30 14:26:28,"Hi Sahabat @Iwan Apriadi, terima kasih atas re...",2026-01-30 15:11:44,3.2.0
96,aa1548bd-727a-4ff9-9fce-ba16b949efbb,Yohanna Audrey Hartini Putri,https://play-lh.googleusercontent.com/a/ACg8oc...,Terlalu lama untuk buka aplikasinya. Trus tiba...,2,2,3.2.0,2026-02-19 12:19:04,"Halo Sahabat @Yohanna Audrey Hartini Putri, mo...",2026-02-19 12:21:48,3.2.0
97,99fef67b-8e48-475a-bf90-46dda0b96a95,Carolline Natalia Sirait,https://play-lh.googleusercontent.com/a-/ALV-U...,"Gajelas, mau top up ewallet gabisa mulu.. pada...",1,0,3.2.0,2026-02-17 21:52:46,"Halo Sahabat @Carolline Natalia Sirait, mohon ...",2026-02-17 22:37:38,3.2.0
98,59033830-0738-4f29-8506-3330f23c3316,Kidal Bolang,https://play-lh.googleusercontent.com/a-/ALV-U...,aplikasi makin lelet. baru keluar sebentar sud...,3,4,3.2.0,2026-02-04 10:00:24,"Halo Sahabat @Kidal Bolang, mohon maaf atas ke...",2026-02-04 10:01:35,3.2.0
99,07e3bd96-4e45-4d83-83e1-5a48b9f794d5,Kupu Bayu,https://play-lh.googleusercontent.com/a/ACg8oc...,kalo mau transaksi sering gagal. saya uninstal...,1,0,3.2.0,2026-02-03 20:24:17,"Halo Sahabat @Kupu Bayu, mohon maaf atas ketid...",2026-02-03 20:27:27,3.2.0

In [9]:
# Mengubah hasil ke DataFrame
apps_df = pd.DataFrame(review2)

# Menyimpan ke CSV
apps_df.to_csv("hasil_Scraping_Livin(Jan-Feb26).csv", index=False)